services:
  redis:
    image: redis:8.2-alpine
    container_name: feedback-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  bullboard:
    container_name: feedback-bullboard
    image: venatum/bull-board
    restart: unless-stopped
    ports:
      - "${BULLBOARD_PORT}:3000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USE_TLS: '${REDIS_SECURE}'
      BULL_PREFIX: ${BULL_PREFIX}
    depends_on:
      - redis

volumes:
  redis_data:
