include:
  - ./shared/database/compose.local.yaml
  - ./shared/queue/compose.local.yaml
  - ./shared/upload/compose.local.yaml

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-server
      args:
        - SERVER_HOST=localhost
        - SERVER_PORT=3001
    command: "pnpm start" 
    env_file:
      - ./apps/server/.env
    container_name: server
    restart: unless-stopped
    ports:
      - 3001:3001
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://$$SERVER_HOST:$$SERVER_PORT/healthcheck",
        ]
    depends_on:
      - postgres

  workers:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-server
      args:
        - SERVER_HOST=localhost
        - SERVER_PORT=3001
    command: "pnpm start:workers" 
    env_file:
      - ./apps/server/.env
    container_name: workers
    restart: unless-stopped
    depends_on:
      - postgres

  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3001
      target: prod-admin
    env_file:
      - ./apps/admin/.env
    container_name: admin
    restart: unless-stopped
    ports:
      - 5174:5174
    command: --brotli --port 5174
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - server
