include:
  - ./shared/database/compose.local.yaml
  - ./shared/queue/compose.local.yaml
  - ./shared/upload/compose.local.yaml

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-server
      args:
        - SERVER_HOST=localhost
        - SERVER_PORT=3001
    command: "pnpm start" 
    env_file:
      - ./apps/server/.env
    container_name: server
    restart: unless-stopped
    ports:
      - 3001:3001
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://$$SERVER_HOST:$$SERVER_PORT/healthcheck",
        ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.server.entrypoints=web-secure"
      - "traefik.http.routers.server.tls.certresolver=tlsresolver"
      - "traefik.http.routers.server.middlewares=chain-authelia@file"
      - "traefik.http.services.server.loadbalancer.server.port=3001"
    depends_on:
      - postgres

  workers:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-server
      args:
        - SERVER_HOST=localhost
        - SERVER_PORT=3001
    command: "pnpm start:workers" 
    env_file:
      - ./apps/server/.env
    container_name: workers
    restart: unless-stopped
    depends_on:
      - postgres

  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VITE_API_BASE_URL: https://admin.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai
      target: prod-admin
    env_file:
      - ./apps/admin/.env
    container_name: admin
    restart: unless-stopped
    ports:
      - 5174:5174
    command: --brotli --port 5174
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.admin.entrypoints=web-secure"
      - "traefik.http.routers.admin.tls.certresolver=tlsresolver"
      - "traefik.http.services.admin.loadbalancer.server.port=5174"
    depends_on:
      - server
