include:
  - ./shared/database/compose.production.yaml
  - ./shared/queue/compose.production.yaml
  - ./shared/minio/compose.production.yaml
  - ./infrastructure/compose.traefik.yaml
  - ./infrastructure/compose.dozzle.yaml
  - ./infrastructure/compose.authelia.yaml
  - ./infrastructure/compose.crowdsec.yaml

services:
  server:
    extends:
      file: compose.local.yaml
      service: server
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.server-external.rule=Host(`api.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`) && (PathPrefix(`/docs`)"
      - "traefik.http.routers.server-external.entrypoints=web-secure"
      - "traefik.http.routers.server-external.tls.certresolver=tlsresolver"
      - "traefik.http.routers.server-external.middlewares=chain-authelia@file"
      - "traefik.http.routers.server-external.service=server"

      - "traefik.http.routers.server-internal.rule=Host(`api.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.server-internal.entrypoints=web-secure"
      - "traefik.http.routers.server-internal.tls.certresolver=tlsresolver"
      - "traefik.http.routers.server-internal.middlewares=chain-no-auth@file"
      - "traefik.http.routers.server-internal.service=server"


      - "traefik.http.services.server.loadbalancer.server.port=3001"

  admin:
    extends:
      file: compose.local.yaml
      service: admin
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VITE_API_BASE_URL: https://api.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai
      target: prod-admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.admin.entrypoints=web-secure"
      - "traefik.http.routers.admin.tls.certresolver=tlsresolver"
      - "traefik.http.routers.admin.middlewares=chain-no-auth@file"
      - "traefik.http.services.admin.loadbalancer.server.port=5174"

  workers:
    extends:
      file: compose.local.yaml
      service: workers

  web:
    extends:
      file: compose.local.yaml
      service: web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.web.entrypoints=web-secure"
      - "traefik.http.routers.web.tls.certresolver=tlsresolver"
      - "traefik.http.routers.web.middlewares=chain-no-auth@file"
      - "traefik.http.services.web.loadbalancer.server.port=5175"

volumes:
  letsencrypt:

secrets:
  authelia_jwt_secret:
    file: ./infrastructure/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: ./infrastructure/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: ./infrastructure/secrets/authelia_storage_encryption_key