services:
  postgres:
    image: "postgres:17.6-bookworm"
    container_name: feedback-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-feedback}
      LC_LANG: ru_RU.UTF-8
    ports:
      - "${POSTGRES_PORT:-6543}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-feedback}"]
      interval: 30s
      timeout: 10s
      retries: 5


  redis:
    image: redis:8.2-alpine
    container_name: feedback-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  bullboard:
    container_name: feedback-bullboard
    image: venatum/bull-board
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feedback-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres


  minio:
    image: minio/minio:latest
    container_name: feedback-minio
    restart: always
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: securedaccesskey:asddasd
      MINIO_ROOT_PASSWORD: mostsecretkey:changemechangeme
    ports:
      - 9000:9000 # API
      - 9001:9001 # Web console
    volumes:
      - minio-data:/data

volumes:
  minio-data:
  postgres_data:
  redis_data:
    external: false
