packages:
  - 'apps/*'
  - 'shared/*'

catalog:
  '@types/node': ^22.10.0
  '@types/better-sqlite3': ^7.6.13
  '@types/nodemailer': ^7.0.1
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@hono/node-server': ^1.19.2
  '@orpc/client': ^1.8.8
  '@orpc/contract': ^1.8.8
  '@orpc/openapi': ^1.8.8
  '@orpc/openapi-client': ^1.8.8
  '@orpc/server': ^1.8.8
  '@orpc/valibot': ^1.8.8
  '@biomejs/biome': 2.2.3
  '@react-email/components': ^0.5.5
  '@react-email/preview-server': ^4.2.12
  '@refinedev/cli': ^2.16.48
  '@refinedev/core': ^5.0.1
  '@refinedev/antd': ^6.0.2
  '@refinedev/react-router': ^2.0.1
  '@vitejs/plugin-react': ^5.0.2
  oxlint: ^1.12.0
  antd: ^5.27.4
  better-auth: ^1.3.9
  better-sqlite3: ^12.2.0
  bullmq: ^5.58.9
  class-variance-authority: ^0.7.1
  dotenv: ^17.2.1
  dotenv-cli: ^10.0.0
  globals: ^16.4.0
  hono: ^4.9.7
  ioredis: ^5.8.0
  kysely: ^0.28.5
  minio: ^8.0.6
  nodemailer: ^7.0.6
  pg: ^8.16.3
  pino: ^9.9.5
  pino-pretty: ^13.1.1
  turbo: ^2.5.6
  react: ^19.1.1
  react-dom: ^19.1.1
  react-router: ^7.9.1
  react-email: ^4.2.12
  tsdown: ^0.15.1
  tsx: ^4.20.5
  typescript: ^5.9.2
  url-join: ^5.0.0
  valibot: ^1.1.0
  vite: ^7.1.5

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: '>=0.25.0'