services:
  postgres:
    extends:
      file: compose.local.yaml
      service: postgres

  pgadmin:
    extends:
      file: compose.local.yaml
      service: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=web-secure
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)
      - traefik.http.routers.pgadmin.middlewares=chain-authelia@file
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=tlsresolver

volumes:
  postgres_data:
