services:
  hotrod:
    image: jaegertracing/example-hotrod:1.61.0
    container_name: hotrod
    restart: unless-stopped
    command: [ "all" ]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318 # In case of external SigNoz or cloud, update the endpoint and access token
    logging:
      options:
        max-size: 50m
        max-file: "3"
    networks:
      - signoz-net
    extra_hosts:
      - host.docker.internal:host-gateway

  load-hotrod:
    image: "signoz/locust:1.2.3"
    container_name: load-hotrod
    restart: unless-stopped
    environment:
      ATTACKED_HOST: http://hotrod:8080
      LOCUST_MODE: standalone
      NO_PROXY: standalone
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--headless -u 10 -r 1"
    logging:
      options:
        max-size: 50m
        max-file: "3"
    networks:
      - signoz-net
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./locust-scripts:/locust

networks:
  signoz-net:
    name: signoz-net
    external: true
