services:
  minio:
    image: minio/minio:latest
    container_name: feedback-minio
    restart: always
    command: server --console-address ":${MINIO_PORT_CONSOLE}" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - ${MINIO_PORT_API}:9000 # API
      - ${MINIO_PORT_CONSOLE}:9001 # Web console
    volumes:
      - minio-data:/data

volumes:
  minio-data:
