services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.111.0
    restart: unless-stopped
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SIGNOZ_COLLECTOR_ENDPOINT=http://host.docker.internal:4317    # In case of external SigNoz or cloud, update the endpoint and access token
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux  # Replace signoz-host with the actual hostname
    # Before exposing the ports, make sure the ports are not used by other services
    # ports:
    #   - "4317:4317"
    #   - "4318:4318"
    logging:
      options:
        max-size: 50m
        max-file: "3"
    networks:
      - signoz-net
    extra_hosts:
      - host.docker.internal:host-gateway

  logspout:
    image: "gliderlabs/logspout:v3.2.14"
    restart: unless-stopped
    command: syslog+tcp://otel-agent:2255
    depends_on:
      - otel-agent
    logging:
      options:
        max-size: 50m
        max-file: "3"
    networks:
      - signoz-net
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  signoz-net:
    name: signoz-net
    external: true
