services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feedback-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: /run/secrets/pgadmin_default_email
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/pgadmin_default_password
    secrets:
      - pgadmin_default_email
      - pgadmin_default_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web-secure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.pgadmin.middlewares=chain-authelia@file"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=tlsresolver"
