services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: feedback-minio
    restart: always
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: /run/secrets/minio_access_key
      MINIO_ROOT_PASSWORD: /run/secrets/minio_secret_key
    secrets:
      - minio_access_key
      - minio_secret_key
    ports:
      - 9000:9000 # API
      - 9001:9001 # Web console
    volumes:
      - minio-data:/data

volumes:
  minio-data:
