services:
  authelia:
    container_name: authelia
    image: authelia/authelia:4.39.4
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # depends_on:
    #  redis:
    #    condition: service_healthy
    # ports:
    #   - "$AUTHELIA_PORT:9091"
    volumes:
      - ./authelia:/config
    environment:
      - TZ="Europe/Moscow"
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
      # - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password
    secrets:
      - authelia_jwt_secret
      - authelia_storage_encryption_key
      - authelia_session_secret
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.authelia.entrypoints=web-secure"
      - "traefik.http.routers.authelia.rule=Host(`authelia.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.authelia.middlewares=chain-no-auth@file" # not chain-authelia!
      - "traefik.http.routers.authelia.tls.certresolver=tlsresolver"

      - "traefik.http.routers.authelia.service=authelia"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"