services:
  postgres:
    image: "postgres:17.6-bookworm"
    build:
      context: ./postgres
    container_name: feedback-postgres
    restart: unless-stopped
    env_file:
      - ../../shared/database/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      DATA_PATH: ./postgres/data
      LOGS_PATH: ./postgres/logs
      WALG_AUTOMATED_BACKUPS: true
      WALG_RETENTION_DAYS: 30
      WALG_LIBSODIUM_KEY: /run/secrets/walg_libsodium_key
      AWS_ACCESS_KEY_ID: /run/secrets/minio_access_key
      AWS_SECRET_ACCESS_KEY: /run/secrets/minio_secret_key
      AWS_ENDPOINT: https://minio.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai
      WALG_S3_PREFIX: s3://backup/postgres-backups
      LC_LANG: ru_RU.UTF-8
    secrets:
      - minio_access_key
      - minio_secret_key
      - walg_libsodium_key
    deploy:
      resources:
        limits:
          memory: 2000M
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/wal-g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
