services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "10101:8080" # LAPI
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/sshd crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/appsec-crs"
    volumes:
      - ./traefik/logs:/logs/traefik:ro
      - /var/log:/var/log:ro
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./crowdsec/config:/etc/crowdsec
