services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "127.0.0.1:9879:9879" # LAPI
      - "6060:6060"
    expose:
      - 9879
      - 7422
    environment:
      BOUNCER_KEY_TRAEFIK: KQyWziTV9wT3cwItTzKuhf/qIPNPDyV6e7OE1C4+s4g
      GID: 1000
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/sshd crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/appsec-crs"
    volumes:
      - /var/log:/var/log:ro
      - ./traefik/logs:/var/log/traefik:ro
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./crowdsec/config:/etc/crowdsec
