http:
  routers:
    web:
      rule: "Host(`xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      entryPoints:
        - web-secure
      middlewares:
        - chain-no-auth
      service: web
      tls:
        certResolver: tlsresolver
  services:
    web:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:5173"